function openDrawer(title,subtitle,summary,history,audit,primary,action){document.getElementById("drawerTitle").textContent=title;document.getElementById("drawerSubtitle").textContent=subtitle;document.getElementById("d-summary").innerHTML=summary;document.getElementById("d-history").innerHTML=history;document.getElementById("d-audit").innerHTML=audit;document.getElementById("drawerPrimary").textContent=primary;document.getElementById("drawerPrimary").onclick=action||(()=>{});document.getElementById("drawerWrap").classList.add("open")}
function closeDrawer(){document.getElementById("drawerWrap").classList.remove("open")}
document.getElementById("drawerWrap").onclick=e=>{if(e.target.id==="drawerWrap")closeDrawer()};
document.querySelectorAll(".drawer-tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".drawer-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".drawer-section").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.getElementById("d-"+t.dataset.tab).classList.add("active")});
function openPerson(id){const p=state.people.find(x=>x.id===id);if(!p)return;openDrawer(p.name,`${p.role} · ${p.status}`,`<div class="kv"><span>Email</span><strong>${p.email}</strong></div><div class="kv"><span>Monthly pay</span><strong>${money(p.pay)}</strong></div><div class="kv"><span>Bank</span>${status(p.bankStatus)}</div><div class="kv"><span>Payroll</span>${status(p.included?"Included":"Not included")}</div><div style="display:flex;gap:8px;margin-top:14px"><button class="btn secondary" onclick="startBankUpdate('${p.id}')">Update bank</button><button class="btn secondary" onclick="toggleInclude('${p.id}')">${p.included?"Remove from payroll":"Include in payroll"}</button></div>`,`<div class="mini-list"><div class="mini-item"><strong>July 2026 · ${money(p.pay)}</strong><small>Settled · 27 Jul 2026</small></div></div>`,`<div class="mini-list"><div class="mini-item"><strong>${p.bankStatus==="Verified"?"Bank verified":"Bank action required"}</strong><small>Current demo state</small></div></div>`,"Preview employee portal",()=>{state.currentPerson=p.id;save();closeDrawer();goPage("employee")})}
function toggleInclude(id){const p=state.people.find(x=>x.id===id);p.included=!p.included;log(p.included?"Added to payroll":"Removed from payroll",`${p.id} · ${p.name}`,"Johannes Oghoro","Employee");save();closeDrawer();render();toast("Payroll updated",`${p.name} ${p.included?"included in":"removed from"} August payroll.`)}
function openPayroll(id){const r=state.payrolls.find(x=>x.id===id);openDrawer(r.period,`${r.people} people · ${money(r.net)}`,`<div class="kv"><span>Pay date</span><strong>${r.date}</strong></div><div class="kv"><span>Funding</span>${status(r.funding)}</div><div class="kv"><span>Approval</span>${status(r.approval)}</div><div class="kv"><span>Status</span>${status(r.status)}</div>`,`<div class="mini-item"><strong>Payroll prepared</strong><small>Scheduler</small></div>`,`<div class="mini-item"><strong>${r.id}</strong><small>Immutable payroll reference</small></div>`,"Open payroll",()=>{closeDrawer();goPage(r.id==="PR-2026-08-001"?"payrollrun":"payroll")})}
function openPayment(id){const p=state.payments.find(x=>x.id===id);openDrawer(p.id,`${p.type} · ${p.status}`,`<div class="kv"><span>Description</span><strong>${p.desc}</strong></div><div class="kv"><span>Amount</span><strong>${money(p.amount)}</strong></div><div class="kv"><span>Date</span><strong>${p.date}</strong></div><div class="kv"><span>Status</span>${status(p.status)}</div><div class="kv"><span>Provider</span><strong>Paystack</strong></div>`,`<div class="mini-item"><strong>Provider event</strong><small>${p.status}</small></div>`,`<div class="mini-item"><strong>Audit record</strong><small>${p.id}</small></div>`,"Close",closeDrawer)}
function previewPayslip(id){const s=state.payslips.find(x=>x.id===id);openDrawer(`${s.person} · ${s.period}`,"Payslip",`<div class="eyebrow">The24thGroup</div><h2 style="font-size:19px;margin:8px 0 16px">Payslip</h2><div class="kv"><span>Employee</span><strong>${s.person}</strong></div><div class="kv"><span>Net pay</span><strong>${money(s.amount)}</strong></div><div class="kv"><span>Period</span><strong>${s.period}</strong></div><div class="kv"><span>Status</span>${status(s.status)}</div>`,`<div class="mini-item"><strong>Generated</strong><small>${s.date}</small></div>`,`<div class="mini-item"><strong>${s.id}</strong><small>Document reference</small></div>`,"Download PDF",()=>toast("Payslip downloaded","Demo download simulated."))}
function startBankUpdate(id){const p=state.people.find(x=>x.id===id);state.currentPerson=id;document.getElementById("resolvedName").value=p.name;document.getElementById("accountNumber").value=p.account?("000000"+p.account).slice(-10):"";closeDrawer();openModal("bankModal")}
document.getElementById("bankConfirm").onclick=()=>{const p=state.people.find(x=>x.id===state.currentPerson),acct=document.getElementById("accountNumber").value.trim();if(!/^\d{10}$/.test(acct)){toast("Check account number","Enter a 10-digit account number for the demo.");return}p.bank=document.getElementById("bankName").value;p.account=acct.slice(-4);p.bankStatus="Verified";log("Bank account verified",`${p.id} · ${p.name}`,"System","Bank account");save();closeModal("bankModal");render();toast("Bank account verified",`${p.name} is now ready for payroll.`)}
document.getElementById("addPersonConfirm").onclick=()=>{const name=document.getElementById("newName").value.trim(),email=document.getElementById("newEmail").value.trim(),role=document.getElementById("newRole").value.trim(),pay=parseInt(document.getElementById("newPay").value.replace(/\D/g,""),10);if(!name||!email||!role||!pay){toast("Complete all fields","Name, email, role and monthly pay are required.");return}const id=`EMP-${String(24+state.people.length).padStart(5,"0")}`;state.people.unshift({id,name,email,role,pay,bank:"",account:"",bankStatus:"Action required",status:"Active",lastPaid:"—",included:true});log("Employee invited",`${id} · ${name}`,"Johannes Oghoro","Employee");save();closeModal("personModal");["newName","newEmail","newRole","newPay"].forEach(x=>document.getElementById(x).value="");render();toast("Invite sent",`${name} was added and needs to add bank details.`)}
