function startFunding(){const run=currentRun();if(issues().length){toast("Resolve readiness first",`${issues().length} people still need attention.`);return}document.getElementById("fundModalBody").innerHTML=`<div class="eyebrow">Payroll amount</div><div class="money" style="font-size:28px;margin-top:6px">${money(calcRunTotal())}</div><div class="muted" style="margin-top:5px">Choose how to fund this payroll.</div><div class="fund-options"><button class="fund-option selected" onclick="chooseFund(this,'Card')"><strong>Card</strong><small>International or Nigerian card via Paystack.</small></button><button class="fund-option" onclick="chooseFund(this,'Bank transfer')"><strong>Bank transfer</strong><small>Fund from a Nigerian bank account.</small></button></div>`;window.demoFundingMethod="Card";document.getElementById("fundConfirm").textContent="Confirm funding";document.getElementById("fundConfirm").onclick=confirmFunding;openModal("fundModal")}
function chooseFund(el,m){document.querySelectorAll(".fund-option").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");window.demoFundingMethod=m}
function confirmFunding(){const run=currentRun();run.funding="Funded";run.status="Funded";state.payments.unshift({id:`FND-2026-08-${String(state.payments.filter(x=>x.type==="Funding").length+1).padStart(3,"0")}`,type:"Funding",desc:"August payroll funding",amount:calcRunTotal(),date:"25 Aug 2026",status:"Settled"});log("Payroll funded",run.id,"Paystack","Payment");save();closeModal("fundModal");render();toast("Payroll funded",`${money(calcRunTotal())} confirmed via ${window.demoFundingMethod}.`)}
function startApproval(){const run=currentRun();if(run.funding!=="Funded"){toast("Funding required","Fund the payroll before approval.");return}document.getElementById("approveModalBody").innerHTML=`<div class="kv"><span>People</span><strong>${includedPeople().length}</strong></div><div class="kv"><span>Net payroll</span><strong>${money(calcRunTotal())}</strong></div><div class="kv"><span>Bank readiness</span><strong>${readyPeople().length}/${includedPeople().length} ready</strong></div><div class="kv"><span>Funding</span>${status(run.funding)}</div><div class="notice">Approval authorises Igho to initiate the employee transfers.</div>`;document.getElementById("approveConfirm").textContent=`Approve ${includedPeople().length} people · ${money(calcRunTotal())}`;document.getElementById("approveConfirm").onclick=confirmApproval;openModal("approveModal")}
function confirmApproval(){const run=currentRun();run.approval="Approved";run.status="Approved";log("Payroll approved",run.id,"Johannes Oghoro","Payroll");save();closeModal("approveModal");render();toast("Payroll approved","The run is ready to pay.")}
function processPayroll(){const run=currentRun();if(run.approval!=="Approved"){toast("Approval required","Approve the payroll first.");return}run.status="Processing";includedPeople().forEach((p,i)=>state.payments.unshift({id:`TRF-2026-08-${String(i+1).padStart(3,"0")}`,type:"Transfer",desc:`${p.name} · August salary`,amount:p.pay,date:"27 Aug 2026",status:"Processing"}));log("Payroll payment initiated",run.id,"Johannes Oghoro","Payroll");save();render();toast("Payments initiated",`${includedPeople().length} transfers are processing.`);setTimeout(settlePayroll,1800)}
function settlePayroll(){const run=currentRun();run.status="Settled";state.payments.filter(p=>p.id.startsWith("TRF-2026-08")).forEach(p=>p.status="Settled");includedPeople().forEach((p,i)=>{p.lastPaid="27 Aug 2026";if(!state.payslips.some(s=>s.person===p.name&&s.period==="August 2026"))state.payslips.unshift({id:`PSL-2026-08-${String(i+1).padStart(3,"0")}`,person:p.name,period:"August 2026",amount:p.pay,date:"27 Aug 2026",status:"Available"})});log("Payroll settled",run.id,"Paystack","Payment");save();render();toast("Payroll complete","All demo transfers settled and August payslips were generated.")}
function createPayroll(){toast("Draft created","In the demo, August is the active payroll run.")}
function savePayrollSettings(){state.settings.payday=document.getElementById("setPayday").value;state.settings.autoPrepare=document.getElementById("setAuto").value;state.settings.approval=document.getElementById("setApproval").value;log("Payroll settings updated","Settings","Johannes Oghoro","System");save();toast("Payroll settings saved","Configuration updated.")}
function saveNotificationSettings(){state.settings.notify=document.getElementById("setNotify").value;save();toast("Notifications saved","Delivery preferences updated.")}
function saveWorkspaceSettings(){state.settings.org=document.getElementById("setOrg").value;state.settings.country=document.getElementById("setCountry").value;save();toast("Workspace saved","Organisation details updated.")}
function saveSecuritySettings(){state.settings.reauth=document.getElementById("setReauth").value;save();toast("Security saved","Security settings updated.")}
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset the Igho demo back to its starting state?")){state=seed();save();render();goPage("overview");toast("Demo reset","The starting state has been restored.")}}
render();
